### ISSUE TITLE
Please change the font

### ISSUE THREAD

**Issue by sakuraimikoto33** [hfcRed/Animation-Repathing#5]
The Kanji font used by Silka Light will be a Chinese font, which will be uncomfortable for Japanese-speaking users.
Please assign a different font for Japanese or use the system font by default and make Silka Light optional.

Use DeepL translation
===original===
Silka Lightで使用される漢字のフォントは中華圏のフォントになってしまい、日本語圏のユーザーにとって違和感のあるものになってしまいます。
日本語に違うフォントを割り当てるか、デフォルトではシステムフォントを使用するようにして、Silka Lightをオプションにしてください。

**Comment by hfcRed** [comment]
Thank you for letting me know, fixed in the latest release
https://github.com/hfcRed/Animation-Repathing/releases/tag/v1.0.3
